service:
  image: ubuntu:18.04
  links:
    - add
    - subtract
    - multiply
    - divide 
 # JUNK command to keep image running (otherwise the image would terminate after compose)
 # easy to debug this way
  command: tail -F anything
add:
  build: .
  dockerfile: Dockerfile_add
  ports:
  - "3000:3000"
subtract:
  build: .
  dockerfile: Dockerfile_sub
  ports:
  - "3001:3001"
multiply:
  build: .
  dockerfile: Dockerfile_mul
  ports:
  - "3002:3002"
divide:
  build: .
  dockerfile: Dockerfile_div
  ports:
  - "3003:3003"